name: speedcubingServer
main: top.speedcubing.server.speedcubingServer
version: 1.0
commands:
  premium:
    usage: /premium
  resetpassword:
    usage: /resetpassword
  discord:
    usage: /discord
  skin:
    usage: /skin
  fly:
    usage: /fly
  hub:
    usage: /hub
    aliases:
      - leave
      - l
      - lobby
      - quit
  announce:
    usage: /announce
  heal:
    usage: /heal
  proxycommand:
    usage: /proxycommand
  nick:
    usage: /nick
  unnick:
    usage: /unnick
  testkb:
    usage: /testkb
  limbo:
    usage: /limbo
  kaboom:
    usage: /kaboom
  deepfry:
    usage: /deepfry
  freeze:
    usage: /freeze
  gmc:
    usage: /gmc
  gms:
    usage: /gms
  gma:
    usage: /gma
  gmsp:
    usage: /gmsp
  2fa:
    usage: /2fa
  image:
    aliases: [ i ]
    usage: /image
  serverconfig:
    usage: /serverconfig
depend:
  - speedcubingLib