name: speedcubingServer
main: top.speedcubing.server.speedcubingServer
version: 1.0
commands:
  premium:
    usage: /premium
  resetpassword:
    usage: /resetpassword
  discord:
    usage: /discord
  skin:
    usage: /skin
  fly:
    usage: /fly
  hub:
    usage: /hub
    aliases:
      - leave
      - l
      - lobby
      - quit
  announce:
    usage: /announce
  heal:
    usage: /heal
  proxycommand:
    usage: /proxycommand
  nick:
    usage: /nick
  unnick:
    usage: /unnick
  testkb:
    usage: /testkb
  limbo:
    usage: /limbo
  kaboom:
    usage: /kaboom
  deepfry:
    usage: /deepfry
  freeze:
    usage: /freeze
  2fa:
    usage: /2fa
  image:
    aliases: [ i ]
    usage: /image
  history:
    usage: /history
  getitemtype:
    usage: /getitemtype
  sendpacket:
    usage: /sendpacket
  serverconfig:
    usage: /serverconfig




depend:
  - speedcubingLib