name: speedcubingServer
main: speedcubing.server.speedcubingServer
version: 1.0
commands:
  premium:
    usage: /premium
  resetpassword:
    usage: /resetpassword
  discord:
    usage: /discord
  skin:
    usage: /skin
  fly:
    usage: /fly
  hub:
    usage: /hub
    aliases:
      - leave
      - l
      - lobby
      - quit
  announce:
    usage: /announce
    aliases:
      - ann
  end:
    usage: /end
  heal:
    usage: /heal
  proxycommand:
    usage: /proxycommand
  nick:
    usage: /nick
  unnick:
    usage: /unnick
  serverinfo:
    usage: /serverinfo
depend:
  - speedcubingLib