name: Build and Package

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Main Repository
      uses: actions/checkout@v4
    #TODO: Finish this.
    - name: Checkout submodules using a PAT
      run: |
        git config --file .gitmodules --get-regexp url | while read url; do
        git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.CI_PAT }}:${{ secrets.CI_PAT }}@github.com\//")
        done
        git submodule sync
        git submodule update --init --recursive
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Install dependency
      run: mvn -B install --file /lib/NameDb/pom.xml
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: the-goodies
        path: target/*.jar
